// Generated by https://quicktype.io

class CreditCard {
  String cardNumber;
  String holder;
  String expirationDate;
  String securityCode;
  String brand;
  String cardToken;
  String customerName;

  CreditCard({
    this.cardNumber,
    this.holder,
    this.expirationDate,
    this.securityCode,
    this.brand,
    this.cardToken,
    this.customerName,
  });

  @override
  String toString() {
    return 'CreditCard{cardNumber: $cardNumber, holder: $holder, expirationDate: $expirationDate, securityCode: $securityCode, brand: $brand, cardToken: $cardToken, customerName: $customerName}';
  }

  factory CreditCard.token(
      {String cardToken, String securityCode, String brand}) {
    return CreditCard(
        cardToken: cardToken, securityCode: securityCode, brand: brand);
  }

  factory CreditCard.fromJson(json) {
    return CreditCard(
        cardNumber: json['CardNumber'] == null ? null : json['CardNumber'],
        holder: json['Holder'] == null ? null : json['Holder'],
        expirationDate:
            json['ExpirationDate'] == null ? null : json['ExpirationDate'],
        securityCode:
            json['SecurityCode'] == null ? null : json['SecurityCode'],
        brand: json['Brand'] == null ? null : json['Brand'],
        customerName:
            json['CustomerName'] == null ? null : json['CustomerName'],
        cardToken: json['CardToken'] == null ? null : json['CardToken']);
  }

  Map<String, dynamic> toJson() {
    return {
      "CardNumber": this.cardNumber == null ? null : this.cardNumber,
      "Holder": this.holder == null ? null : this.holder,
      "ExpirationDate":
          this.expirationDate == null ? null : this.expirationDate,
      "SecurityCode": this.securityCode == null ? null : this.securityCode,
      "Brand": this.brand == null ? null : this.brand,
      "CardToken": this.cardToken == null ? null : this.cardToken,
      "CustomerName": this.customerName == null ? null : this.customerName,
    };
  }
}
