// Generated by https://quicktype.io

import 'dart:convert';

import 'Customer.dart';
import 'Payment.dart';

class Sale {
  String MerchantOrderId;
  Customer customer;
  Payment payment;


  Sale({
    this.MerchantOrderId,
    this.customer,
    this.payment,

  }) {
    if (this.customer == null) this.customer = Customer();
    if (this.payment == null) this.payment = Payment();
  }

  toJson() {
    return {
      "MerchantOrderId":
          this.MerchantOrderId == null ? null : this.MerchantOrderId,
      "Customer": this.customer == null ? null : this.customer.toJson(),
      "Payment": this.payment == null ? null : this.payment.toJson(),

    };
  }

  factory Sale.fromJson(j) {
    j = json.decode(j.toString());
    print(j);
    print(j["Customer"]);
    print(j["Payment"]);
    return Sale(
        MerchantOrderId: j['MerchantOrderId'] == null
            ? null
            : j["MerchantOrderId"].toString(),
        customer:
            j['Customer'] == null ? null : Customer.fromJson(j["Customer"]),
        payment: j['Payment'] == null
            ? null
            : Payment.fromJson(
                j["Payment"],
              ),
        );
  }

  @override
  String toString() {
    return 'Sale{merchantOrderId: $MerchantOrderId, customer: $customer, payment: $payment}';
  }
}
