List<Banco> bancos = [
  Banco(numero: '001', nome: 'Banco do Brasil 001'),
  Banco(numero: '003', nome: 'Banco da Amazônia 003'),
  Banco(numero: '004', nome: 'Banco do Nordeste do Brasil 004'),
  Banco(numero: '012', nome: 'BANCO STANDARD DE INVESTIMENTOS S.A. 012'),
  Banco(numero: '014', nome: 'NATIXIS BRASIL S.A. 014'),
  Banco(numero: '019', nome: 'BANCO AZTECA DO BRASIL S.A. 019'),
  Banco(
      numero: '021',
      nome: 'BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO 021'),
  Banco(numero: '024', nome: 'BANCO DE PERNAMBUCO S.A. - BANDEPE 024'),
  Banco(numero: '025', nome: 'BANCO ALFA S.A. 025'),
  Banco(numero: '029', nome: 'BANCO BANERJ S.A. 029'),
  Banco(numero: '031', nome: 'BANCO BEG S.A. 031'),
  Banco(numero: '033', nome: 'BANCO SANTANDER (BRASIL) S.A. 033'),
  Banco(numero: '036', nome: 'BANCO BRADESCO BBI S.A. 036'),
  Banco(numero: '037', nome: 'BANCO DO ESTADO DO PARÁ S.A. 037'),
  Banco(numero: '040', nome: 'BANCO CARGILL S.A. 040'),
  Banco(numero: '041', nome: 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. 041'),
  Banco(numero: '044', nome: 'BANCO BVA S.A. 044'),
  Banco(numero: '045', nome: 'BANCO OPPORTUNITY S.A. 045'),
  Banco(numero: '047', nome: 'BANCO DO ESTADO DE SERGIPE S.A. 047'),
  Banco(numero: '062', nome: 'HIPERCARD BANCO MÚLTIPLO S.A. 062'),
  Banco(numero: '063', nome: 'BANCO IBI S.A. - BANCO MÚLTIPLO 063'),
  Banco(numero: '065', nome: 'BANCO LEMON S.A. 065'),
  Banco(numero: '066', nome: 'BANCO MORGAN STANLEY S.A. 066'),
  Banco(numero: '069', nome: 'BPN BRASIL BANCO MÚLTIPLO S.A. 069'),
  Banco(numero: '070', nome: 'BRB - BANCO DE BRASILIA S.A. 070'),
  Banco(numero: '072', nome: 'BANCO RURAL MAIS S.A. 072'),
  Banco(numero: '073', nome: 'BB BANCO POPULAR DO BRASIL S.A. 073'),
  Banco(numero: '074', nome: 'BANCO J. SAFRA S.A. 074'),
  Banco(numero: '075', nome: 'BANCO CR2 S/A 075'),
  Banco(numero: '076', nome: 'BANCO KDB DO BRASIL S.A. 076'),
  Banco(numero: '077', nome: 'BANCO INTERMEDIUM S/A 077'),
  Banco(numero: '078', nome: 'BES INVESTIMENTO DO BRASIL S.A. - 078'),
  Banco(numero: '079', nome: 'JBS BANCO S/A 079'),
  Banco(numero: '081', nome: 'CONCÓRDIA BANCO S.A. 081'),
  Banco(numero: '082', nome: 'BANCO TOPÁZIO S.A. 082'),
  Banco(numero: '083', nome: 'BANCO DA CHINA BRASIL S.A 083'),
  Banco(numero: '096', nome: 'BANCO BM&F DE SERV DE LIQ E CUSTÓDIA S.A. 096'),
  Banco(numero: '104', nome: 'CAIXA ECONOMICA FEDERAL 104'),
  Banco(numero: '107', nome: 'BANCO BBM S/A 107'),
  Banco(numero: '151', nome: 'BANCO NOSSA CAIXA S.A. 151'),
  Banco(numero: '204', nome: 'BANCO BRADESCO CARTÕES S.A. 204'),
  Banco(numero: '208', nome: 'BANCO UBS PACTUAL S.A. 208'),
  Banco(numero: '212', nome: 'BANCO MATONE S.A. 212'),
  Banco(numero: '213', nome: 'BANCO ARBI S.A. 213'),
  Banco(numero: '214', nome: 'BANCO DIBENS S.A. 214'),
  Banco(numero: '215', nome: 'BANCO SUDAMERIS S.A. 215'),
  Banco(numero: '217', nome: 'BANCO JOHN DEERE S.A. 217'),
  Banco(numero: '218', nome: 'BANCO BONSUCESSO S.A. 218'),
  Banco(numero: '222', nome: 'BANCO CALYON BRASIL S.A. 222'),
  Banco(numero: '224', nome: 'BANCO FIBRA S.A. 224'),
  Banco(numero: '225', nome: 'BANCO BRASCAN S.A. 225'),
  Banco(numero: '229', nome: 'BANCO CRUZEIRO DO SUL S.A. 229'),
  Banco(numero: '230', nome: 'UNICARD BANCO MÚLTIPLO S.A. 230'),
  Banco(numero: '233', nome: 'BANCO GE CAPITAL S.A. 233'),
  Banco(numero: '237', nome: 'BANCO BRADESCO S.A. 237'),
  Banco(numero: '241', nome: 'BANCO CLASSICO S.A. 241'),
  Banco(numero: '243', nome: 'BANCO MÁXIMA S.A. 243'),
  Banco(numero: '246', nome: 'BANCO ABC BRASIL S.A. 246'),
  Banco(numero: '248', nome: 'BANCO BOAVISTA INTERATLANTICO S.A. 248'),
  Banco(numero: '249', nome: 'BANCO INVESTCRED UNIBANCO S.A. 249'),
  Banco(numero: '250', nome: 'BANCO SCHAHIN S.A. 250'),
  Banco(numero: '254', nome: 'PARANÁ BANCO S.A. Banco Múltiplo'),
  Banco(numero: '263', nome: 'BANCO CACIQUE S.A. Banco Múltiplo'),
  Banco(numero: '265', nome: 'BANCO FATOR S.A. Banco Múltiplo'),
  Banco(numero: '266', nome: 'BANCO CEDULA S.A. Banco Múltiplo'),
  Banco(numero: '300', nome: 'BANCO DE LA NACION ARGENTINA 300'),
  Banco(numero: '318', nome: 'BANCO BMG S.A. 318'),
  Banco(numero: '320', nome: 'BANCO INDUSTRIAL E COMERCIAL S.A. 320'),
  Banco(numero: '341', nome: 'BANCO ITAÚ S.A. 341'),
  Banco(numero: '366', nome: 'BANCO SOCIETE GENERALE BRASIL S.A. 366'),
  Banco(numero: '370', nome: 'BANCO WESTLB DO BRASIL S.A. 370'),
  Banco(numero: '376', nome: 'BANCO J.P. MORGAN S.A. 376'),
  Banco(numero: '389', nome: 'BANCO MERCANTIL DO BRASIL S.A. 389'),
  Banco(numero: '394', nome: 'BANCO FINASA BMC S.A. 394'),
  Banco(numero: '399', nome: 'HSBC BANK BRASIL S.A. 399'),
  Banco(numero: '409', nome: 'UNIBANCO-UNIAO DE BANCOS BRASILEIROS S.A. 409'),
  Banco(numero: '412', nome: 'BANCO CAPITAL S.A. 412'),
  Banco(numero: '422', nome: 'BANCO SAFRA S.A. 422'),
  Banco(numero: '453', nome: 'BANCO RURAL S.A. 453'),
  Banco(numero: '456', nome: 'BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S/A 456'),
  Banco(numero: '464', nome: 'BANCO SUMITOMO MITSUI BRASILEIRO S.A. 464'),
  Banco(numero: '473', nome: 'BANCO CAIXA GERAL - BRASIL S.A. 473'),
  Banco(numero: '477', nome: 'CITIBANK N.A. Banco Comercial Estrangeiro - 477'),
  Banco(numero: '487', nome: 'DEUTSCHE BANK S.A. - BANCO ALEMAO 487'),
  Banco(numero: '488', nome: 'JPMORGAN CHASE BANK, NATIONAL ASSOCIATION 488'),
  Banco(numero: '492', nome: 'ING BANK N.V. 492'),
  Banco(numero: '494', nome: 'BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY 494'),
  Banco(numero: '495', nome: 'BANCO DE LA PROVINCIA DE BUENOS AIRES 495'),
  Banco(numero: '505', nome: 'BANCO CREDIT SUISSE (BRASIL) S.A. 505'),
  Banco(numero: '600', nome: 'BANCO LUSO BRASILEIRO S.A. 600'),
  Banco(numero: '604', nome: 'BANCO INDUSTRIAL DO BRASIL S.A. 604'),
  Banco(numero: '610', nome: 'BANCO VR S.A. 610'),
  Banco(numero: '611', nome: 'BANCO PAULISTA S.A. 611'),
  Banco(numero: '612', nome: 'BANCO GUANABARA S.A. 612'),
  Banco(numero: '613', nome: 'BANCO PECUNIA S.A. 613'),
  Banco(numero: '623', nome: 'BANCO PANAMERICANO S.A. 623'),
  Banco(numero: '626', nome: 'BANCO FICSA S.A. 626'),
  Banco(numero: '630', nome: 'BANCO INTERCAP S.A. 630'),
  Banco(numero: '633', nome: 'BANCO RENDIMENTO S.A. 633'),
  Banco(numero: '634', nome: 'BANCO TRIANGULO S.A. 634'),
  Banco(numero: '637', nome: 'BANCO SOFISA S.A. 637'),
  Banco(numero: '638', nome: 'BANCO PROSPER S.A. 638'),
  Banco(numero: '641', nome: 'BANCO ALVORADA S.A. 641'),
  Banco(numero: '643', nome: 'BANCO PINE S.A. 643'),
  Banco(numero: '653', nome: 'BANCO INDUSVAL S.A. 653'),
  Banco(numero: '654', nome: 'BANCO A.J. RENNER S.A. 654'),
  Banco(numero: '655', nome: 'BANCO VOTORANTIM S.A. 655'),
  Banco(numero: '707', nome: 'BANCO DAYCOVAL S.A. 707'),
  Banco(numero: '719', nome: 'BANIF - BANCO INTERNACIONAL DO FUNCHAL S.A. 719'),
  Banco(numero: '721', nome: 'BANCO CREDIBEL S.A. 721'),
  Banco(numero: '734', nome: 'BANCO GERDAU S.A 734'),
  Banco(numero: '735', nome: 'BANCO POTTENCIAL S.A. 735'),
  Banco(numero: '738', nome: 'BANCO MORADA S.A 738'),
  Banco(numero: '739', nome: 'BANCO BGN S.A. 739'),
  Banco(numero: '740', nome: 'BANCO BARCLAYS S.A. 740'),
  Banco(numero: '741', nome: 'BANCO RIBEIRAO PRETO S.A. 741'),
  Banco(numero: '743', nome: 'BANCO SEMEAR S.A. 743'),
  Banco(numero: '745', nome: 'BANCO CITIBANK S.A. 745'),
  Banco(numero: '746', nome: 'BANCO MODAL S.A. 746'),
  Banco(numero: '747', nome: 'BANCO RABOBANK INTERNATIONAL BRASIL S.A. 747'),
  Banco(numero: '748', nome: 'BANCO COOPERATIVO SICREDI S.A. 748'),
  Banco(numero: '749', nome: 'BANCO SIMPLES S.A. 749'),
  Banco(numero: '751', nome: 'DRESDNER BANK BRASIL S.A. 751'),
  Banco(numero: '752', nome: 'BANCO BNP PARIBAS BRASIL S.A. 752'),
  Banco(numero: '753', nome: 'NBC BANK BRASIL S. A. 753'),
  Banco(numero: '756', nome: 'BANCO COOPERATIVO DO BRASIL S.A. 756'),
  Banco(numero: '757', nome: 'BANCO KEB DO BRASIL S.A. 757')
];

class Banco {
  static List<Banco> getSuggestions(String query) {
    List<Banco> matches = List();
    matches.addAll(bancos);

    matches
        .retainWhere((s) => s.nome.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }

  String numero;
  String nome;

  @override
  String toString() {
    return 'Banco{numero: $numero, nome: $nome}';
  }

  Banco({this.numero, this.nome});
}
