name: ufly_motorista
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: 0.6.1
  cloud_functions: 0.6.0
  flutter_swiper: ^1.1.4
  flutter_local_notifications: 0.8.3
  flutter_spinkit: 3.1.0
  bloc_pattern: ^1.5.2
  firebase_storage: 4.0.0
  firebase_database: 4.0.0
  firebase_remote_config: 0.2.0+7
  firebase_analytics: 5.0.2
  firebase_messaging: 5.1.8
  firebase_performance: 0.3.0+5
  stripe_payment: 1.0.7
  firebase_auth: 0.18.0+1
  firebase_core: 0.5.0
  rxdart: ^0.22.0
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.21+6
  location: 2.3.5
  get_it: 4.0.4
  i18n_extension: 1.4.4
  cloud_firestore: 0.14.0+2
  google_fonts: ^0.5.0+1
  cupertino_icons: ^0.1.3
  fluttertoast: ^3.1.3
  image_picker: 0.6.7+4
  font_awesome_flutter: 8.5.0
  flutter_masked_text: 0.8.0
  timeago: ^2.0.10
  short_stream_builder: ^0.0.1
  expandable: 4.1.4
  random_string: 2.0.1
  country_code_picker: 1.4.0
  cached_network_image: '2.0.0-rc'
  material_design_icons_flutter: 3.2.4495
  progress_dialog: ^1.2.0
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: 0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  fonts:
    - family: Malgun
      fonts:
        - asset: fonts/malgun.ttf
    - family: BankGothic
      fonts:
        - asset: fonts/BankGothic.ttf

  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
